name: todo_backend
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  array_frequency_calculator: ^1.0.0
  aqueduct: ^4.0.0-b1
  postgres: ^2.1.1
  jaguar_jwt: ^2.1.6

#dependency_overrides:
#  postgres: 2.2.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1
